language: python
cache: pip
python: "3.6.4"

before_install:
  - "mv travis_secrets.yaml secrets.yaml"
  - "sudo mkdir -p /ssl/ && sudo touch /ssl/fullchain.pem"
  - "sudo mkdir -p /ssl/ && sudo touch /ssl/privkey.pem"
install:
  - pip3 install homeassistant
  - pip3 install colorlog
after_install:
  - "hass --version"
  - hass -c config/ --script check_config --info all