- id: '1560486441509'
  alias: SJ Enter Office
  trigger:
  - entity_id: device_tracker.sooraj
    event: enter
    platform: zone
    zone: zone.office
  condition:
  - after: 07:00:00
    before: '11:00:00'
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: input_boolean.work_from_home
    state: 'off'
  action:
  - data:
      message: Sooraj Has Reached Office
      target:
      - '+13035177090'
      - '+13035179860'
    service: notify.sms
  - data:
      entity_id: automation.sj_enter_office
    service: automation.turn_off
  mode: single
- id: '1560486572636'
  alias: SJ Leave Office
  trigger:
  - entity_id: device_tracker.sooraj
    event: leave
    platform: zone
    zone: zone.office
  condition:
  - after: '13:00:00'
    before: '18:00:00'
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: input_boolean.work_from_home
    state: 'off'
  action:
  - data:
      message: Sooraj Has Left Office
      target:
      - '+13035177090'
      - '+13035179860'
    service: notify.sms
  - data:
      entity_id: automation.sj_leave_office
    service: automation.turn_off
- id: '1560486643605'
  alias: ' SJ Enter Home'
  trigger:
  - entity_id: device_tracker.sooraj
    event: enter
    platform: zone
    zone: zone.home
  condition:
  - after: '13:00:00'
    before: '17:00:00'
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: state
    entity_id: input_boolean.work_from_home
    state: 'off'
  action:
  - data:
      message: Sooraj Has Reached Home
      target:
      - '+13035177090'
      - '+13035179860'
    service: notify.sms
  - data:
      entity_id: automation.sj_enter_home
    service: automation.turn_off
- id: '1560706564185'
  alias: SJ Reset Presence Detection
  trigger:
  - at: 01:00:00
    platform: time
  condition: []
  action:
  - data:
      entity_id:
      - automation.sj_leave_office
      - automation.sj_enter_home
      - automation.sj_enter_office
    service: automation.turn_on
- id: '1560721960186'
  alias: TV On
  trigger:
  - entity_id: input_boolean.tvpower
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      host: 10.0.1.54
      packet:
      - JgCMAJSUEjcSOBE4EhMRExITEhMSEhI4FDUUNhMRFBEUERQRExEUERQ1FBEUERQRFBAVEBQRFDUVEBQ1FTUUNRU0FTUUNRUABfyTlBI4ETgSNxITEhMSExETEhMSNxI4EjcSExITERMSExITERQROBITERMSExITERQRExI4ERMSOBE4EjcSOBI3EjgRAA0FAAAAAAAAAAAAAAAA
    service: broadlink.send
  initial_state: true
- id: '1560722338415'
  alias: TV Off
  trigger:
  - entity_id: input_boolean.tvpower
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      host: 10.0.1.54
      packet:
      - JgCMAJOUEjgSNxI4ERQRExITEhMRExI4ETgSOBETEhMSExEUERMSExI3EhMSExETEhMSExITETgSExE4EjcSOBI3EjgROBIABf+TlBI4ETgSNxITEhMSExETEhMSNxI4EjcSExITERMSExITEhMROBITERMSExITEhMRExI4ERMSOBI3EjgROBI4ETgSAA0FAAAAAAAAAAAAAAAA
    service: broadlink.send
  initial_state: true
- id: '1561950212865'
  alias: Spotlights On
  trigger:
  - entity_id: input_boolean.spotpower
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      host: 10.0.1.54
      packet:
      - JgBQAAABJZISExETEhITEhITEhITEhEUETgRNxM3EjcSNxI3EjcSNxMSEhMRExITERQRExISEhMSNxI3EjgRNxI3EzcSNxE4EgAFEgABJUkRAA0FAAAAAAAAAAA=
    service: broadlink.send
  initial_state: true
- id: '1561950417809'
  alias: Spotlights Off
  trigger:
  - entity_id: input_boolean.spotpower
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      host: 10.0.1.54
      packet:
      - JgBQAAABJJMTERITEhITEhITERMSExEUEjYSNxQ2EjcROBI3EzYSNxI4ERMSExETEhITEhITEhITEhE4EjcTNhI3EzcSNxE4EgAFEgABJUkRAA0FAAAAAAAAAAA=
    service: broadlink.send
  initial_state: true
- id: '1565893219431'
  alias: Patio Lights On
  trigger:
  - event: sunset
    platform: sun
  condition:
  - condition: state
    entity_id: light.patio_lights
    state: 'off'
  action:
  - data: {}
    entity_id: light.patio_lights
    service: light.turn_on
- id: '1565893600335'
  alias: Ceiling Lamp On
  trigger:
  - event: sunset
    platform: sun
  condition:
  - condition: state
    entity_id: light.ceiling_lamp
    state: 'off'
  action:
  - data: {}
    entity_id: light.ceiling_lamp
    service: light.turn_on
- id: '1571960345827'
  alias: Bedroom Lamp Off
  description: ''
  trigger:
  - at: 06:45:00
    platform: time
  condition:
  - condition: state
    entity_id: light.bedroom_lamp
    state: 'on'
  action:
  - data:
      entity_id: light.bedroom_lamp
    service: light.turn_off
- id: '1575695078004'
  alias: Sync Tasmota
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      payload: ''
      topic: cmnd/tasmotas/state
    service: mqtt.publish
- id: '1576394669002'
  alias: Server Rack Temp
  description: ''
  trigger:
  - above: '80'
    entity_id: sensor.server_rack_temperature
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Server Rack Temp Is {{ states('sensor.server_rack_temperature') }}
    service: notify.mobile_app_sj_ise
  mode: single
- id: '1577042979082'
  alias: HA Stop
  description: ''
  trigger:
  - event: shutdown
    platform: homeassistant
  condition: []
  action:
  - data:
      message: Home-Assistant is going down!
    service: notify.mobile_app_sj_ise
  mode: single
- id: '1577043173279'
  alias: HA Start
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      message: Home Assistant is online!
    service: notify.mobile_app_sj_ise
  mode: single
- id: '1583679033042'
  alias: Storage Light On
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_storage_door_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.storage_light
    state: 'off'
  action:
  - data: {}
    entity_id: light.storage_light
    service: light.turn_on
- id: '1583679147628'
  alias: Storage Light Off
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_storage_door_sensor
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: light.storage_light
    state: 'on'
  action:
  - data: {}
    entity_id: light.storage_light
    service: light.turn_off
- id: '1590822055372'
  alias: Turn Lights Off
  description: ''
  trigger:
  - at: '22:30:00'
    platform: time
  condition: []
  action:
  - data: {}
    service: light.turn_off
    entity_id:
    - light.patio_lights
    - light.deck_lights
    - light.ceiling_lamp
- id: '1594054377786'
  alias: Set Theme
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: noctis
    service: frontend.set_theme
- id: '1600456936550'
  alias: Update Available
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_sj_ise
    data:
      message: You have a new update available - {{ states('sensor.latest_ha_version')
        }}
  mode: single
- id: '1601795094670'
  alias: Garage Open For 30
  description: ''
  trigger:
  - entity_id: sensor.garage_door_status
    platform: state
    to: open
    for: 00:30:00
  condition: []
  action:
  - service: script.notify_all
    data:
      message: Garage is open for more than 30 minutes
  mode: single
- id: '1607842337831'
  alias: Front Door Status
  description: ''
  trigger:
  - entity_id: binary_sensor.wyze_front_door_sensor
    from: 'on'
    platform: state
    to: 'off'
  - platform: state
    entity_id: binary_sensor.wyze_front_door_sensor
    from: 'off'
    to: 'on'
  condition:
  - after: '22:00:00'
    before: 07:00:00
    condition: time
  action:
  - data:
      message: "{% if is_state('binary_sensor.wyze_front_door_sensor', 'on') %}\n\
        \  Front door is open\n{% else %}\n  Front door is closed\n{% endif %}"
    service: script.notify_all
  mode: single
- id: '1607842673148'
  alias: Garage Status
  description: ''
  trigger:
  - entity_id: sensor.garage_door_status
    from: open
    platform: state
    to: closed
  - entity_id: sensor.garage_door_status
    from: closed
    platform: state
    to: open
  condition: []
  action:
  - service: script.notify_all
    data:
      message: "{% if is_state('sensor.garage_door_status', 'open') %}\n  Garage is\
        \ open\n{% else %}\n  Garage is closed\n{% endif %}"
  mode: single
