- platform: foscam
  name: Baby
  ip: 10.0.1.80
  port: 8180
  username: !secret fcuname
  password: !secret fcpw
- platform: foscam
  name: Front Door
  ip: 10.0.1.81
  port: 8280
  username: !secret fcuname
  password: !secret fcpw
- platform: foscam
  name: Living Room
  ip: 10.0.1.82
  port: 8380
  username: !secret fcuname
  password: !secret fcpw  
- platform: combined
  base_address: !secret url
  entities:
    - camera.baby
    - camera.front_door
    - camera.living_room
