homeassistant:
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    # - type: legacy_api_password
    #   api_password: !secret httppw

http:
#  base_url: !secret url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: False
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies: 10.0.1.4

#default_config:
config:
updater:
conversation:
history:
logbook:
sun:
map:
cloud:
system_health:
mobile_app:
person:
frontend:
  themes: !include_dir_merge_named themes
logger:
  default: info
  # logs:
  #   custom_components.wyzesense: debug
  #   wyzesense.gateway: debug

recorder:
  db_url: !secret mysql
#  purge_keep_days: 3
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - group
    entities:
      - sun.sun
      - sensor.home_eta
      - binary_sensor.remote_ui

tplink:
  light:
    - host: 10.0.40.18

weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily

ifttt:
  key: !secret ifkey

nest:
  client_id: !secret nest_cid
  client_secret: !secret nest_sec

# withings:
#   client_id: !secret withid
#   client_secret: !secret withsecret
#   profiles:
#     - sooraj
#     - arleepta

eufy:
  username: !secret eufyuname
  password: !secret eufypw

zwave:
  usb_path: /dev/ttyACM0

alarm_control_panel:
  - platform: manual
    name: Home Alarm

#image_processing:
#  - platform: facebox
#    ip_address: !secret mbox
#    port: 443
#    source:
#      - entity_id: camera.front_door

tts: !include tts.yaml
binary_sensor: !include binary_sensors.yaml
notify: !include notify.yaml
#device_tracker: !include device_tracker.yaml
camera: !include cameras.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
input_boolean: !include input_boolean.yaml
rest_command: !include rest_api.yaml
light: !include lights.yaml
#switch: !include switches.yaml
#alert: !include alerts.yaml