homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: !secret elev
  unit_system: imperial
  time_zone: !secret tz
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret httppw

zone:
  name: Home
  latitude: !secret hzlat
  longitude: !secret hzlong
  radius: 300
  icon: mdi:home
  track_ios: true

zone 2:
  name: Office
  latitude: !secret ozlat
  longitude: !secret ozlong
  radius: 200
  icon: mdi:domain
  track_ios: true

zone 3:
  name: Library
  latitude: !secret liblat
  longitude: !secret liblong
  radius: 200
  icon: mdi:library
  track_ios: true

http:
  base_url: !secret url
  ip_ban_enabled: False
  login_attempts_threshold: 3
  use_x_forwarded_for: true
  trusted_proxies: 10.0.1.4

frontend:
  themes: !include_dir_merge_named themes
config:
updater:
conversation:
history:
logbook:
sun:
map:
cloud:
system_health:
mobile_app:
person:
#shelly:
tplink:
wemo:
  static:
    - 10.0.1.78

logger:
  default: info
#  logs:
#    custom_components.wyzesense: debug
#    wyzesense.gateway: debug  

recorder:
  db_url: mysql://hassio:QDNNj8ag1XwLwNwK@db.schettada.net/hassio?charset=utf8
  purge_keep_days: 3
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - group
    entities:
      - sun.sun
      - sensor.home_eta
      - binary_sensor.remote_ui

weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily

ifttt:
  key: !secret ifkey

nest:
  client_id: !secret nest_cid
  client_secret: !secret nest_sec

withings:
  client_id: !secret withid
  client_secret: !secret withsecret
  profiles:
    - sooraj
    - arleepta

eufy:
  username: !secret eufyuname
  password: !secret eufypw

zwave:
  usb_path: /dev/ttyACM0

alarm_control_panel:
  - platform: manual
    name: Home Alarm

#image_processing:
#  - platform: facebox
#    ip_address: !secret mbox
#    port: 443
#    source:
#      - entity_id: camera.front_door

panel_iframe:
  mdiindex:
    title: MDI Icon Index
    icon: mdi:vector-square
    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html

tts: !include tts.yaml
binary_sensor: !include binary_sensors.yaml
notify: !include notify.yaml
device_tracker: !include device_tracker.yaml
camera: !include cameras.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
input_boolean: !include input_boolean.yaml
#alert: !include alerts.yaml
