- platform: mqtt
  name: "Garage"
  command_topic: "SJGarage/IN/STATE"
  state_topic: "SJGarage/OUT/STATE"
  state_open: "OPEN"
  state_closed: "CLOSED"
  payload_open: "open"
  payload_close: "close"
  device_class: "garage"

# - platform: opengarage
#   covers:
#     garage:
#       host: garage.schettada.io
#       device_key: opendoor
#       name: Left Garage Door