esphome:
  name: esp2
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "HyperLoop"
  password: "Musafir@85"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP Fallback Hotspot"
    password: "gaoMZkbrnrMN"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: status
    name: "ESP2 Status"

text_sensor:
  - platform: version
    name: "ESP2 Version"
    icon: mdi:chip
  - platform: wifi_info
    ip_address:
      name: "ESP2 IP Address"
