esphome:
  name: livingroom
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "Voyager"
  password: !secret wifi

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livingroom Fallback Hotspot"
    password: "maXEIA4ndSwo"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:

binary_sensor:
  - platform: status
    name: "Livingroom BLE Tracker Status"
  - platform: ble_presence
    mac_address: 10:30:25:DD:57:EA
    name: "Sooraj Office Phone"
  - platform: ble_presence
    mac_address: 8C:86:1E:A9:85:3E
    name: "Sooraj Personal Phone"
    
text_sensor:
  - platform: version
    name: "Livingroom BLE Tracker Version"
    icon: mdi:chip
  - platform: wifi_info
    ip_address:
      name: "Livingroom BLE Tracker IP Address"
