version: 5
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: Mud1ait9phu0soh7aeCu6yel0oojee3koxeileigohn9xeeBaeshe6laiquooL3c
serial:
  port: tcp://zigbee.crashpad.im:6638
  adapter: ember
  baudrate: 115200
  rtscts: false
advanced:
  log_level: info
  channel: 25
  network_key:
    - 144
    - 221
    - 249
    - 151
    - 243
    - 99
    - 19
    - 47
    - 170
    - 159
    - 29
    - 194
    - 247
    - 93
    - 27
    - 102
  pan_id: 34058
  ext_pan_id:
    - 228
    - 98
    - 135
    - 16
    - 102
    - 250
    - 106
    - 222
frontend:
  enabled: true
  port: 8099
homeassistant:
  enabled: true
devices:
  '0x8c6fb9fffe262da7':
    friendly_name: Pooja Room Motion Sensor
  '0x002446fffd09435b':
    friendly_name: Garage Door Lock
  '0x0017880109196488':
    friendly_name: Basement Stairs Multi Sensor
  '0x00124b00259092fb':
    friendly_name: Basement Zigbee Router
  '0x0017880109197eb3':
    friendly_name: Basement Multi Sensor
  '0x00158d0009108ee3':
    friendly_name: Rack Light Switch
  '0xdc8e95fffe3ed0cd':
    friendly_name: Rack Light
